apiVersion: v1
kind: Service
metadata:
   name: javawebappsvc
spec:
        # type: ClusterIP
  type: NodePort
  selector:
     app: javawebapp
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30500
