apiVersion: v1
kind: Pod
metadata:
   name: java-web-app-pod
   labels:
     app: javawebapp
spec:
  containers:
     - name: javawebappcontainer
       image: saleem786/java-web-app-img
       ports:
         - containerPort: 8080
