apiVersion: v1
kind: Pod
metadata:
   name: maven-web-app-pod
   labels:
     app: mavenwebapp
spec:
  containers:
     - name: mavenwebappcontainer
       image: ashokit/mavenwebapp
       ports:
         - containerPort: 8080
